### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Callumk7** [Callumk7/game-master#104]
This task / epic is going to handle setting up permissions in the app. Other tasks will be linked to this one, as the main parent. You can read about the broader strokes here:

https://whimsical.com/epic-editor-app-UHa4LPGHjhTcSBC4poseJK

- [x] Add members to games through a user search
- [x] Add a role property to the user join table
- [x] Add a property to entities to cover their visbility and access levels
- [x] Add filtering for logged in to only show them notes that they are allowed to see
- [x] route handling for insufficient permissions
- [x] non-editable note view for notes where the user does not have permission to edit
- [ ] Notification centre to handle game and note invites

**Comment by Callumk7** [comment]
#107

**Comment by Callumk7** [comment]
#110 Completed the UI part of adding users and choosing their role
